### ISSUE TITLE
能否更新一下版本?

### ISSUE THREAD

**Issue by hou476466741** [jinzaz/MqttNet.DependencyInjection#1]
现在的版本是3.1 能否更新到最新版本呢？

**Comment by jinzaz** [comment]
可以的 有时间整一下

**Comment by hou476466741** [comment]
最近这几天要使用MQTT，能否最近更新一下，非常感谢啦。

**Comment by hou476466741** [comment]
我看了一下，版本好像没有更新，是不是改动太大了？

**Comment by jinzaz** [comment]
升级net8.0了

**Comment by jinzaz** [comment]
等一下，你说的版本是 mqttnet 版本 还是 .net

**Comment by hou476466741** [comment]
我说的是MQTTnet版本，能不能更新成新版。

**Comment by jinzaz** [comment]
更新了

**Comment by hou476466741** [comment]
大佬，非常感谢您更新，能否增加服务端？

**Comment by jinzaz** [comment]
服务端使用 MQTTnet 的就好了，比自己去实现要可靠点
https://github.com/dotnet/MQTTnet/blob/master/Samples/Server/Server_ASP_NET_Samples.cs
